// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6D-UFFUcBaFHzjhZohnjpiHthvVcUaE',
    appId: '1:1070620386754:web:1c57f57262af415594625b',
    messagingSenderId: '1070620386754',
    projectId: 'myvote-9ae34',
    authDomain: 'myvote-9ae34.firebaseapp.com',
    storageBucket: 'myvote-9ae34.firebasestorage.app',
    measurementId: 'G-4JXG4ZP820',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8QCeMCsKjZq0QyNV570bA3NOwBy68PA',
    appId: '1:1070620386754:android:c3cbafd944d3ac3494625b',
    messagingSenderId: '1070620386754',
    projectId: 'myvote-9ae34',
    storageBucket: 'myvote-9ae34.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH6D-UFFUcBaFHzjhZohnjpiHthvVcUaE',
    appId: '1:1070620386754:web:d3e6d0d3bbd1808b94625b',
    messagingSenderId: '1070620386754',
    projectId: 'myvote-9ae34',
    authDomain: 'myvote-9ae34.firebaseapp.com',
    storageBucket: 'myvote-9ae34.firebasestorage.app',
    measurementId: 'G-W75FSFB1JR',
  );
}
